# -*- coding: utf-8 -*-
"""transfer_learningipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FZSXydIg1d8BdC4oBwu6LmjM2FERI9mQ
"""

#!unzip archive.zip

from pathlib import Path
data_path=Path("")
image_path=data_path / "DATA"

import os
def check_data(dir_path):
  for dirpath, dirnames, filenames in os.walk(dir_path):
    print(f"# of directories: {len(dirnames)} and {len(filenames)} images in '{dirpath}'.")

check_data(image_path)

train_dir=image_path /"train"
test_dir=image_path / "test"

train_dir

from torch.utils.data import DataLoader
from torchvision import datasets, transforms
from torchvision.transforms import v2
import torchvision
import torch

manuel_transform=v2.Compose([
    v2.Resize((224,224)),
    v2.ToImage(),
    v2.ToDtype(dtype=torch.float32,scale=True),
    v2.Normalize(mean=[0.485, 0.456, 0.406],std=[0.229, 0.224, 0.225])
])

from torch.utils.data import DataLoader

NUM_WORKERS = os.cpu_count()

def create_dataloaders(
    train_dir: str,
    test_dir: str,
    transform: transforms.Compose,
    batch_size: int,
    num_workers: int=NUM_WORKERS
):
  # Use ImageFolder to create dataset(s)
  train_data = datasets.ImageFolder(train_dir, transform=transform)
  test_data = datasets.ImageFolder(test_dir, transform=transform)

  # Get class names
  class_names = train_data.classes

  # Turn images into data loaders
  train_dataloader = DataLoader(
      train_data,
      batch_size=batch_size,
      shuffle=True,
      num_workers=num_workers,
      pin_memory=True,
  )
  test_dataloader = DataLoader(
      test_data,
      batch_size=batch_size,
      shuffle=False, # don't need to shuffle test data
      num_workers=num_workers,
      pin_memory=True,
  )

  return train_dataloader, test_dataloader, class_names

train_dataloader, test_dataloader, class_names=create_dataloaders(train_dir=train_dir,test_dir=test_dir,
                                                                  transform=manuel_transform,batch_size=32
                                                                  )

class_names

train_dataloader

train_dataloader.dataset

device=torch.device("cuda" if torch.cuda.is_available() else "cpu")

device

"""MODEL AĞIRLIKARINI YÜKLÜYORUZ."""

weights=torchvision.models.EfficientNet_B0_Weights.DEFAULT

weights

transformlar=weights.transforms()

transformlar

train_dataloader, test_dataloader, class_names=create_dataloaders(train_dir=train_dir,test_dir=test_dir,
                                                                  transform=manuel_transform,
                                                                  batch_size=32
                                                                  )



"""MODELİ KENDİSİ YÜKLÜYORUZ"""

model=torchvision.models.efficientnet_b0(weights=weights).to(device=device)

model



from torchinfo import summary

"""MODELİN ÖZETİNE BAKIYORUZ.. KATMANLARIN TÜMÜ EĞİTİLMİŞ.ANCAK BİZ BU KATMANLARI DONDURACAĞIZ.
EĞİTECEĞİZ SADECE SON KATMAN SINIFLANDIRMA KATMANI OLACAK
"""

summary(model=model,input_size=(32,3,224,224),
        col_names=["input_size", "output_size", "num_params", "trainable"]
        )

"""KATMANLARI DONDURUYORUZ."""

for param in model.features.parameters():
  param.requires_grad = False

summary(model=model,input_size=(32,3,224,224),
        col_names=["input_size", "output_size", "num_params", "trainable"]
        )

"""SON KATMANI KENDİ SINIF SAYIMIZA GÖRE DEĞİŞTİRMEMEİZ GEREKİR."""

output_shape=len(class_names)



model.classifier=torch.nn.Sequential(
    torch.nn.Dropout(p=0.2,inplace=True),
    torch.nn.Linear(in_features=1280,out_features=output_shape,bias=True)
).to(device)

summary(model=model,input_size=(32,3,224,224),
        col_names=["input_size", "output_size", "num_params", "trainable"]
        )

from torch import nn

loss_fn=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=0.001)

def train_step(model: torch.nn.Module,
               dataloader: torch.utils.data.DataLoader,
               loss_fn: torch.nn.Module,
               optimizer: torch.optim.Optimizer,
               device: torch.device):
    # Put model in train mode
    model.train()

    # Setup train loss and train accuracy values
    train_loss, train_acc = 0, 0

    # Loop through data loader data batches
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # 1. Forward pass
        y_pred = model(X)

        # 2. Calculate  and accumulate loss
        loss = loss_fn(y_pred, y)
        train_loss += loss.item()

        # 3. Optimizer zero grad
        optimizer.zero_grad()

        # 4. Loss backward
        loss.backward()

        # 5. Optimizer step
        optimizer.step()

        # Calculate and accumulate accuracy metrics across all batches
        y_pred_class = torch.argmax(torch.softmax(y_pred, dim=1), dim=1)
        train_acc += (y_pred_class == y).sum().item() / len(y_pred)

    # Adjust metrics to get average loss and accuracy per batch
    train_loss = train_loss / len(dataloader)
    train_acc = train_acc / len(dataloader)
    return train_loss, train_acc


def test_step(model: torch.nn.Module,
              dataloader: torch.utils.data.DataLoader,
              loss_fn: torch.nn.Module,
              device: torch.device):
    # Put model in eval mode
    model.eval()

    # Setup test loss and test accuracy values
    test_loss, test_acc = 0, 0

    # Turn on inference context manager
    with torch.inference_mode():
        # Loop through DataLoader batches
        for batch, (X, y) in enumerate(dataloader):
            X, y = X.to(device), y.to(device)
            # 1. Forward pass
            test_pred_logits = model(X)

            # 2. Calculate and accumulate loss
            loss = loss_fn(test_pred_logits, y)
            test_loss += loss.item()

            # Calculate and accumulate accuracy
            test_pred_labels = test_pred_logits.argmax(dim=1)
            test_acc += ((test_pred_labels == y).sum().item() / len(test_pred_labels))

    # Adjust metrics to get average loss and accuracy per batch
    test_loss = test_loss / len(dataloader)
    test_acc = test_acc / len(dataloader)
    return test_loss, test_acc


def train(model: torch.nn.Module,
          train_dataloader: torch.utils.data.DataLoader,
          test_dataloader: torch.utils.data.DataLoader,
          optimizer: torch.optim.Optimizer,
          device: torch.device,
          loss_fn: torch.nn.Module = nn.CrossEntropyLoss(),
          epochs: int = 5):
    # 2. Create empty results dictionary
    results = {"train_loss": [],
               "train_acc": [],
               "test_loss": [],
               "test_acc": []
               }

    # 3. Loop through training and testing steps for a number of epochs
    for epoch in range(epochs):
        train_loss, train_acc = train_step(model=model,
                                           dataloader=train_dataloader,
                                           loss_fn=loss_fn,
                                           optimizer=optimizer,
                                           device=device)
        test_loss, test_acc = test_step(model=model,
                                        dataloader=test_dataloader,
                                        loss_fn=loss_fn,
                                        device=device)

        # 4. Print out what's happening
        print(
            f"Epoch: {epoch + 1} | "
            f"train_loss: {train_loss:.4f} | "
            f"train_acc: {train_acc:.4f} | "
            f"test_loss: {test_loss:.4f} | "
            f"test_acc: {test_acc:.4f}"
        )

        # 5. Update results dictionary
        # Ensure all data is moved to CPU and converted to float for storage
        results["train_loss"].append(train_loss.item() if isinstance(train_loss, torch.Tensor) else train_loss)
        results["train_acc"].append(train_acc.item() if isinstance(train_acc, torch.Tensor) else train_acc)
        results["test_loss"].append(test_loss.item() if isinstance(test_loss, torch.Tensor) else test_loss)
        results["test_acc"].append(test_acc.item() if isinstance(test_acc, torch.Tensor) else test_acc)

    # 6. Return the filled results at the end of the epochs
    return results

result=train(model=model,
             train_dataloader=train_dataloader,
             test_dataloader=test_dataloader,
             optimizer=optimizer,
             device=device,
             loss_fn=loss_fn,
             epochs=10
             )

